defaults:
  - _self_
  - data_loading: data_loading
  - data_loading@preprocessing: preprocessing_x
  - model: model
  - training: training_x
  - logging: logging
  #- inference: inference

hydra:
  run:
    dir: ./outputs
  output_subdir: null
